"""Evidence dossier PDF.

The representment packet a merchant submits to the issuer: a cover
summary, the transaction/order/delivery facts, the evidence exhibits
(each citing its source record), the Visa CE3.0 status when relevant,
and the dispute economics. Built with fpdf2 (pure-python, no system
deps). Amounts are written as "Rs" - core PDF fonts are latin-1 and do
not carry the rupee glyph, and "Rs" is unambiguous on a bank-facing
document.

Nothing here is submitted automatically: the PDF is a work product for a
human to review and file. It reads only from records already on the
case, so it cannot contain a fact the evidence engine did not source.
"""

from __future__ import annotations

from fpdf import FPDF

from ..models.entities import Chargeback

INK = (33, 53, 84)
MUTED = (120, 130, 150)
RULE = (220, 226, 236)
GOOD = (15, 138, 76)
BAD = (196, 48, 47)
BLUE = (48, 94, 255)

SUPPORT_LABEL = {
    "merchant": "Supports merchant", "customer": "Supports customer",
    "neutral": "Context", "missing": "Missing",
}


def _rs(v) -> str:
    try:
        return f"Rs {float(v):,.2f}"
    except (TypeError, ValueError):
        return str(v)


_PT_MM = 0.3528   # points -> millimetres


def _wordmark(pdf: "FPDF", size: float = 15.0):
    """The ChargeLens wordmark: lowercase 'charge' in ink + 'lens' in
    blue, with the signature blue underline under 'lens'. No icon - pure
    type, matching the app's logo."""
    x0, y0 = pdf.get_x(), pdf.get_y()
    pdf.set_font("Helvetica", "B", size)
    cap = size * _PT_MM * 0.72               # approx cap height in mm
    baseline = y0 + cap
    charge_w = pdf.get_string_width("charge")
    lens_w = pdf.get_string_width("lens")

    pdf.set_text_color(*INK)
    pdf.text(x0, baseline, "charge")
    pdf.set_text_color(*BLUE)
    pdf.text(x0 + charge_w, baseline, "lens")

    # signature underline beneath 'lens' only
    thick = max(0.4, size * _PT_MM * 0.11)
    uy = baseline + size * _PT_MM * 0.16
    pdf.set_fill_color(*BLUE)
    try:
        pdf.rect(x0 + charge_w + 0.2, uy, lens_w - 0.3, thick,
                 style="F", round_corners=True, corner_radius=thick / 2)
    except TypeError:                        # older fpdf without rounding
        pdf.rect(x0 + charge_w + 0.2, uy, lens_w - 0.3, thick, style="F")

    pdf.set_xy(x0, uy + thick + 1.4)


class _Doc(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_y(8)
        _wordmark(self, size=9)
        self.set_xy(self.l_margin, 9)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 8, f"Evidence dossier - {self._case_id}", align="R",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*RULE)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin,
                  self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*MUTED)
        self.multi_cell(
            0, 4,
            "Generated by ChargeLens from records on file. Synthetic "
            "demonstration data. For human review before submission - "
            "nothing is filed automatically.",
            align="C")
        self.set_x(-30)
        self.cell(0, 4, f"Page {self.page_no()}", align="R")


def _h(pdf: _Doc, text: str):
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*INK)
    pdf.cell(0, 7, text, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*RULE)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(2)


def _kv(pdf: _Doc, key: str, value: str):
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(52, 5.5, key)
    pdf.set_text_color(*INK)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5.5, _ascii(value), new_x="LMARGIN", new_y="NEXT")


def _ascii(s) -> str:
    """fpdf core fonts are latin-1; map the rupee sign to 'Rs' and drop
    anything else outside the range rather than showing '?'."""
    return (str(s).replace("₹", "Rs ")
            .encode("latin-1", "replace").decode("latin-1"))


def build_dossier(case: Chargeback, detail: dict) -> bytes:
    pdf = _Doc(format="A4")
    pdf._case_id = case.id
    risk = detail.get("risk") or {}
    econ = (risk.get("economics") or {}) if risk else {}
    ce3 = (risk.get("ce3") or {}) if risk else {}
    pdf._respond_by = (detail.get("respond_by") or "n/a")[:10]

    pdf.set_auto_page_break(True, margin=18)
    pdf.add_page()

    # ---- brand header ----------------------------------------------------
    _wordmark(pdf, size=16)
    pdf.set_xy(pdf.w - pdf.r_margin - 60, pdf.t_margin + 1)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(60, 4, "Dispute intelligence", align="R",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(pdf.w - pdf.r_margin - 60, pdf.t_margin + 5)
    pdf.cell(60, 4, "Defense-only - human-in-the-loop", align="R")
    pdf.set_xy(pdf.l_margin, pdf.t_margin + 13)
    pdf.set_draw_color(*BLUE)
    pdf.set_line_width(0.6)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(5)

    # ---- title -----------------------------------------------------------
    pdf.set_font("Helvetica", "B", 17)
    pdf.set_text_color(*INK)
    pdf.cell(0, 9, "Chargeback Representment Dossier",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, f"Dispute {case.id} - prepared for issuer review",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ---- case summary ----------------------------------------------------
    _h(pdf, "1. Dispute summary")
    _kv(pdf, "Dispute reference", case.external_ref or case.id)
    _kv(pdf, "Reason", case.reason.replace("_", " ").title())
    _kv(pdf, "Disputed amount", _rs(case.disputed_amount))
    _kv(pdf, "Rail / network", f"{case.rail} / {case.network or 'n/a'}")
    _kv(pdf, "Response deadline", pdf._respond_by)
    _kv(pdf, "Customer claim", f'"{case.claim_description}"')
    if risk:
        _kv(pdf, "Model risk score",
            f"{risk['risk_score']:.0%} (band: {risk['band']}, "
            f"model v{risk.get('model_version', '?')})")

    # ---- recommendation --------------------------------------------------
    _h(pdf, "2. Recommendation")
    rec = (case.recommendation or "review").upper()
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*(GOOD if case.recommendation == "contest" else INK))
    pdf.cell(0, 6, rec, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*INK)
    pdf.multi_cell(0, 5, _ascii(case.recommendation_reason or ""),
                   new_x="LMARGIN", new_y="NEXT")

    # ---- economics -------------------------------------------------------
    if econ:
        _h(pdf, "3. Dispute economics")
        _kv(pdf, "Modeled win probability", f"{econ['p_win']:.0%}")
        _kv(pdf, "Expected recovery", _rs(econ["expected_recovery_inr"]))
        _kv(pdf, "Cost to contest",
            f"{_rs(econ['contest_cost_inr'])} (fee not refunded on a win)")
        _kv(pdf, "Expected value", _rs(econ["ev_contest_inr"]))
        _kv(pdf, "Break-even win prob.", f"{econ['break_even_p_win']:.1%}")

    # ---- CE3.0 -----------------------------------------------------------
    if ce3 and ce3.get("status") != "not_applicable":
        _h(pdf, "4. Visa Compelling Evidence 3.0")
        _kv(pdf, "Status", ce3["status"].replace("_", " ").title())
        if ce3.get("matched_main"):
            _kv(pdf, "Matched main elements",
                ", ".join(ce3["matched_main"]))
        if ce3.get("matched_secondary"):
            _kv(pdf, "Matched secondary", ", ".join(ce3["matched_secondary"]))
        if ce3.get("qualifying_transactions"):
            _kv(pdf, "Qualifying prior txns",
                ", ".join(ce3["qualifying_transactions"]))
        if ce3.get("missing"):
            _kv(pdf, "Missing to qualify", "; ".join(ce3["missing"]))
        _kv(pdf, "Note", ce3.get("note", ""))

    # ---- evidence exhibits ----------------------------------------------
    _h(pdf, "5. Evidence exhibits")
    evidence = detail.get("evidence", [])
    if not evidence:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(0, 6, "No evidence collected (case not yet investigated).",
                 new_x="LMARGIN", new_y="NEXT")
    for i, e in enumerate(evidence, 1):
        pdf.set_font("Helvetica", "B", 9)
        color = GOOD if e["supports"] == "merchant" else (
            BAD if e["supports"] == "customer" else MUTED)
        pdf.set_text_color(*color)
        pdf.cell(8, 5.5, f"{i}.")
        pdf.set_text_color(*INK)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5.5, _ascii(e["statement"]),
                       new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(pdf.l_margin + 8)
        pdf.set_font("Helvetica", "I", 7.5)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(
            0, 4,
            f"{SUPPORT_LABEL.get(e['supports'], e['supports'])} - "
            f"{e['strength']} - source {e['source']}",
            new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    out = pdf.output()
    return bytes(out)
