"""Synthetic chargeback case generator.

DISCLOSURE: every record produced by this module is SYNTHETIC. No real
customer, transaction, or payment data is used anywhere in this project.

Design goals (in order):

1. Labels must come from latent behavioural scenarios, never from the
   features themselves. A case is generated by first sampling *why* the
   dispute happened (the scenario), then sampling every observable field
   from scenario-conditional distributions. The model only ever sees the
   observables, so the learning problem is genuinely inferential.

2. Distributions must overlap. Abusive claimants sometimes have long,
   clean histories (the "opportunist" archetype); legitimate claimants
   sometimes look suspicious (a mis-delivered package that scans as
   "delivered"). Evidence is missing at realistic rates on both sides.

3. Signals must interact. For "product not received" claims, a confirmed
   delivery points TOWARD abuse; for "unauthorized transaction" claims,
   a familiar device points toward abuse while an unfamiliar device and
   high velocity point toward a genuine fraud victim (whom the merchant
   should NOT fight). Linear models struggle with this on purpose - it
   justifies the model comparison in train.py.

4. Ground-truth labels carry ~3% noise, because real dispute outcomes
   are themselves imperfect labels.

Label definition:
    label_abusive = 1  -> the dispute is illegitimate (friendly fraud /
                          abuse); the merchant is entitled to contest it.
    label_abusive = 0  -> the dispute is legitimate; the merchant should
                          accept it or refund the customer.

The latent `scenario` column is retained for error analysis ONLY and
must never be used as a model feature (enforced by tests).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path(__file__).resolve().parents[1] / "data"

REASON_PNR = "product_not_received"
REASON_UNAUTH = "unauthorized_transaction"
REASON_NAD = "product_not_as_described"

PRODUCT_CATEGORIES = [
    "electronics", "fashion", "home", "beauty", "sports", "books", "toys",
]
PAYMENT_METHODS = ["credit_card", "debit_card", "upi", "netbanking", "wallet"]
CITIES = [
    "Bangalore", "Mumbai", "Delhi", "Chennai", "Hyderabad", "Pune",
    "Kolkata", "Ahmedabad", "Jaipur", "Kochi",
]

# scenario name -> (label_abusive, sampling weight)
SCENARIOS = {
    # -- abusive: merchant is entitled to contest ------------------------
    "friendly_fraud_pnr": (1, 0.17),   # got the goods, claims non-receipt
    "opportunist_abuse": (1, 0.10),    # long clean history, tries it once
    "false_unauthorized": (1, 0.10),   # own purchase, claims "not me"
    # -- legitimate: the customer is telling the truth -------------------
    "true_fraud_victim": (0, 0.13),    # card really was stolen
    "lost_package": (0, 0.28),         # carrier lost / mis-delivered it
    "defective_item": (0, 0.22),       # item genuinely not as described
}

LABEL_NOISE = 0.03  # fraction of ground-truth labels flipped


@dataclass
class GenConfig:
    n_cases: int = 12_000
    seed: int = 42
    start_date: datetime = field(
        default_factory=lambda: datetime(2026, 1, 1))
    span_days: int = 180


def _lognormal(rng, mean, sigma, size=None):
    return rng.lognormal(mean=mean, sigma=sigma, size=size)


def _sample_scenario(rng) -> str:
    names = list(SCENARIOS)
    weights = np.array([SCENARIOS[n][1] for n in names])
    return rng.choice(names, p=weights / weights.sum())


def _customer_profile(rng, scenario: str) -> dict:
    """Account tenure / history, conditioned on scenario but overlapping."""
    if scenario in ("friendly_fraud_pnr", "false_unauthorized"):
        # skew newer, but with a long tail of established accounts
        account_age = rng.gamma(shape=1.6, scale=160)
        prior_cb_rate = 0.55
        prior_return_lam = 1.8
        failed_pay_lam = 0.9
    elif scenario == "opportunist_abuse":
        # deliberately looks like a model customer
        account_age = rng.gamma(shape=4.0, scale=220)
        prior_cb_rate = 0.12
        prior_return_lam = 0.8
        failed_pay_lam = 0.25
    elif scenario == "true_fraud_victim":
        # victim's own account is ordinary; tenure is irrelevant to theft
        account_age = rng.gamma(shape=3.0, scale=200)
        prior_cb_rate = 0.10
        prior_return_lam = 0.7
        failed_pay_lam = 0.35
    else:  # lost_package, defective_item
        account_age = rng.gamma(shape=3.2, scale=190)
        prior_cb_rate = 0.15
        prior_return_lam = 1.0
        failed_pay_lam = 0.3

    account_age = float(np.clip(account_age, 2, 2600))
    # order count grows with tenure, noisily
    monthly_rate = rng.gamma(shape=1.8, scale=0.8)
    previous_orders = int(rng.poisson(max(monthly_rate * account_age / 30, 0.2)))
    previous_chargebacks = int(rng.poisson(prior_cb_rate))
    previous_returns = int(rng.poisson(prior_return_lam))
    previous_failed_payments = int(rng.poisson(failed_pay_lam))
    avg_order_value = float(np.clip(_lognormal(rng, 7.6, 0.7), 150, 200_000))
    return {
        "account_age_days": round(account_age, 1),
        "previous_orders": previous_orders,
        "previous_chargebacks": previous_chargebacks,
        "previous_returns": previous_returns,
        "previous_failed_payments": previous_failed_payments,
        "avg_order_value": round(avg_order_value, 2),
    }


def _reason_for(rng, scenario: str) -> str:
    if scenario == "friendly_fraud_pnr":
        return rng.choice([REASON_PNR, REASON_NAD], p=[0.85, 0.15])
    if scenario == "opportunist_abuse":
        return rng.choice([REASON_PNR, REASON_NAD], p=[0.55, 0.45])
    if scenario == "false_unauthorized":
        return REASON_UNAUTH
    if scenario == "true_fraud_victim":
        return REASON_UNAUTH
    if scenario == "lost_package":
        return REASON_PNR
    return REASON_NAD  # defective_item


def _amount_for(rng, scenario: str) -> float:
    # abusive disputes skew to higher tickets, with heavy overlap
    mu = {"friendly_fraud_pnr": 8.6, "opportunist_abuse": 9.1,
          "false_unauthorized": 8.8, "true_fraud_victim": 9.0,
          "lost_package": 8.1, "defective_item": 8.0}[scenario]
    return float(np.clip(_lognormal(rng, mu, 0.85), 199, 350_000))


def _delivery_block(rng, scenario: str, reason: str) -> dict:
    """Delivery observables. Confirmation strength is the key evidence."""
    if scenario in ("friendly_fraud_pnr", "opportunist_abuse"):
        # goods really arrived; carrier evidence exists but is imperfect
        status = rng.choice(["delivered", "delivered", "delivered", "unknown"],
                            p=[0.55, 0.25, 0.12, 0.08])
        confirmation = rng.choice(["signed", "otp", "photo", "none"],
                                  p=[0.30, 0.28, 0.22, 0.20])
        has_tracking = rng.random() < 0.93
    elif scenario == "lost_package":
        status = rng.choice(
            ["failed", "in_transit", "unknown", "delivered", "returned_to_sender"],
            p=[0.30, 0.22, 0.18, 0.22, 0.08])  # 22% mis-delivery scans "delivered"
        confirmation = (
            rng.choice(["photo", "none"], p=[0.25, 0.75])
            if status == "delivered" else "none")
        has_tracking = rng.random() < 0.85
    elif scenario in ("true_fraud_victim", "false_unauthorized"):
        # goods went somewhere; for real fraud, to the fraudster's address
        status = rng.choice(["delivered", "in_transit", "unknown"],
                            p=[0.75, 0.15, 0.10])
        confirmation = rng.choice(["signed", "otp", "photo", "none"],
                                  p=[0.22, 0.20, 0.23, 0.35])
        has_tracking = rng.random() < 0.90
    else:  # defective_item - delivery is not in dispute
        status = "delivered"
        confirmation = rng.choice(["signed", "otp", "photo", "none"],
                                  p=[0.28, 0.27, 0.25, 0.20])
        has_tracking = rng.random() < 0.95

    days_to_deliver = (
        float(np.clip(rng.gamma(2.2, 1.6), 1, 21))
        if status in ("delivered",) else np.nan)
    return {
        "delivery_status": status,
        "delivery_confirmation": confirmation,
        "has_tracking": int(has_tracking),
        "days_to_deliver": (round(days_to_deliver, 1)
                            if not np.isnan(days_to_deliver) else np.nan),
    }


def _device_block(rng, scenario: str) -> dict:
    if scenario == "true_fraud_victim":
        device_seen = rng.random() < 0.12          # fraudster's device
        shared = int(rng.poisson(1.6))
        geo_km = float(np.clip(_lognormal(rng, 5.4, 1.1), 0, 9000))
        velocity = int(np.clip(rng.poisson(3.2) + 1, 1, 30))
        addr_match = rng.random() < 0.35
    elif scenario == "false_unauthorized":
        device_seen = rng.random() < 0.82          # their own device
        shared = int(rng.poisson(0.3))
        geo_km = float(np.clip(_lognormal(rng, 2.6, 1.2), 0, 9000))
        velocity = int(np.clip(rng.poisson(0.7) + 1, 1, 30))
        addr_match = rng.random() < 0.86
    elif scenario in ("friendly_fraud_pnr", "opportunist_abuse"):
        device_seen = rng.random() < 0.78
        shared = int(rng.poisson(0.5))
        geo_km = float(np.clip(_lognormal(rng, 3.0, 1.2), 0, 9000))
        velocity = int(np.clip(rng.poisson(0.9) + 1, 1, 30))
        addr_match = rng.random() < 0.80
    else:  # honest shoppers
        device_seen = rng.random() < 0.85
        shared = int(rng.poisson(0.25))
        geo_km = float(np.clip(_lognormal(rng, 2.8, 1.1), 0, 9000))
        velocity = int(np.clip(rng.poisson(0.6) + 1, 1, 30))
        addr_match = rng.random() < 0.88
    return {
        "device_seen_before": int(device_seen),
        "device_shared_accounts": shared,
        "ip_geo_distance_km": round(geo_km, 1),
        "txns_last_24h": velocity,
        "shipping_billing_match": int(addr_match),
    }


def _claim_delay(rng, scenario: str) -> float:
    """Days between delivery (or expected delivery) and the claim."""
    if scenario in ("friendly_fraud_pnr", "opportunist_abuse"):
        d = rng.gamma(3.2, 4.5)          # tends to wait; mean ~14d
    elif scenario == "false_unauthorized":
        d = rng.gamma(2.5, 6.0)          # waits for the statement
    elif scenario == "true_fraud_victim":
        d = rng.gamma(1.8, 5.5)          # notices on the statement
    elif scenario == "lost_package":
        d = rng.gamma(1.5, 2.8)          # complains fast; mean ~4d
    else:
        d = rng.gamma(2.0, 3.5)
    return float(np.clip(d, 0.2, 90))


_CLAIM_TEXT = {
    REASON_PNR: [
        "I never received this package.",
        "The order shows delivered but nothing arrived at my address.",
        "Item was not delivered to me.",
    ],
    REASON_UNAUTH: [
        "I did not make this transaction.",
        "This charge is not mine, my card was used without permission.",
        "Unauthorized payment on my account.",
    ],
    REASON_NAD: [
        "The product I received is completely different from the listing.",
        "Item arrived damaged / not as described.",
        "Product quality does not match what was advertised.",
    ],
}


def generate(cfg: GenConfig) -> pd.DataFrame:
    rng = np.random.default_rng(cfg.seed)
    rows = []
    for i in range(cfg.n_cases):
        scenario = _sample_scenario(rng)
        label = SCENARIOS[scenario][0]
        reason = _reason_for(rng, scenario)
        cust = _customer_profile(rng, scenario)
        amount = _amount_for(rng, scenario)
        delivery = _delivery_block(rng, scenario, reason)
        device = _device_block(rng, scenario)
        delay = _claim_delay(rng, scenario)

        order_ts = cfg.start_date + timedelta(
            days=float(rng.uniform(0, cfg.span_days)),
            seconds=float(rng.uniform(0, 86_400)))
        shipped_ts = order_ts + timedelta(days=float(rng.uniform(0.2, 3.0)))
        if delivery["delivery_status"] == "delivered":
            delivered_ts = shipped_ts + timedelta(
                days=delivery["days_to_deliver"] or 3.0)
            claim_anchor = delivered_ts
        else:
            delivered_ts = None
            claim_anchor = shipped_ts + timedelta(days=5.0)
        claim_ts = claim_anchor + timedelta(days=delay)

        ship_city = rng.choice(CITIES)
        bill_city = ship_city if device["shipping_billing_match"] else (
            rng.choice([c for c in CITIES if c != ship_city]))

        # ground-truth noise: real dispute outcomes are imperfect labels
        observed_label = label if rng.random() >= LABEL_NOISE else 1 - label

        rows.append({
            "case_id": f"CB-{10_000 + i}",
            "customer_id": f"CUST-{rng.integers(1, cfg.n_cases):05d}-{i % 7}",
            "transaction_id": f"TXN-{20_000 + i}",
            "order_id": f"ORD-{30_000 + i}",
            "scenario": scenario,
            "label_abusive": observed_label,
            "chargeback_reason": reason,
            "claim_description": str(rng.choice(_CLAIM_TEXT[reason])),
            "disputed_amount": round(amount, 2),
            "currency": "INR",
            "payment_method": str(rng.choice(
                PAYMENT_METHODS, p=[0.34, 0.22, 0.28, 0.09, 0.07])),
            "payment_status": "captured",
            "product_category": str(rng.choice(PRODUCT_CATEGORIES)),
            "quantity": int(np.clip(rng.poisson(0.4) + 1, 1, 6)),
            "shipping_city": ship_city,
            "billing_city": bill_city,
            "order_ts": order_ts.isoformat(timespec="seconds"),
            "shipped_ts": shipped_ts.isoformat(timespec="seconds"),
            "delivered_ts": (delivered_ts.isoformat(timespec="seconds")
                             if delivered_ts else None),
            "claim_ts": claim_ts.isoformat(timespec="seconds"),
            "claim_delay_days": round(delay, 1),
            **cust,
            **delivery,
            **device,
        })
    df = pd.DataFrame(rows)

    # one customer id can appear on several cases; make history consistent
    # enough for grouping without inventing a full simulation of each user
    return df


def split_by_customer(df: pd.DataFrame, seed: int,
                      train=0.70, val=0.15):
    """Group split on customer_id so no customer straddles splits."""
    rng = np.random.default_rng(seed + 1)
    customers = df["customer_id"].unique()
    rng.shuffle(customers)
    n = len(customers)
    train_c = set(customers[: int(n * train)])
    val_c = set(customers[int(n * train): int(n * (train + val))])
    part = df["customer_id"].map(
        lambda c: "train" if c in train_c else ("val" if c in val_c else "test"))
    return part


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n-cases", type=int, default=12_000)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    cfg = GenConfig(n_cases=args.n_cases, seed=args.seed)
    df = generate(cfg)
    df["split"] = split_by_customer(df, cfg.seed)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    out = DATA_DIR / "cases.csv"
    df.to_csv(out, index=False)

    manifest = {
        "synthetic": True,
        "disclosure": "All records are synthetically generated; no real "
                      "customer or payment data is present.",
        "n_cases": int(len(df)),
        "seed": cfg.seed,
        "label_noise": LABEL_NOISE,
        "class_balance": {
            "abusive": int(df["label_abusive"].sum()),
            "legitimate": int((1 - df["label_abusive"]).sum()),
            "abusive_rate": round(float(df["label_abusive"].mean()), 4),
        },
        "splits": df["split"].value_counts().to_dict(),
        "split_strategy": "grouped by customer_id (no customer overlap)",
        "scenario_counts": df["scenario"].value_counts().to_dict(),
        "generated_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
    }
    (DATA_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(json.dumps(manifest, indent=2))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
